### ISSUE TITLE
**ParseError:** Unclosed '{' on line 3

### ISSUE THREAD

**Issue by skerbis** [alexplusde/staff#3]
**ParseError:** Unclosed '{' on line 3
**File:** redaxo/src/addons/staff/boot.php
**Line:** 8

<details>
<summary>Stacktrace</summary>

| Function                 | File                                     | Line     |
| ------------------------ | ---------------------------------------- | -------- |
| rex_package->includeFile | redaxo/src/core/lib/packages/package.php | 421      |
| rex_package->boot        | redaxo/src/core/packages.php             | 27       |
| {closure}                | redaxo/src/core/lib/util/timer.php       | 57       |
| rex_timer::measure       | redaxo/src/core/packages.php             | 28       |
| {closure}                | redaxo/src/core/lib/util/timer.php       | 57       |
| rex_timer::measure       | redaxo/src/core/packages.php             | 30       |
| include_once             | redaxo/src/core/backend.php              | 200      |
| require                  | redaxo/src/core/boot.php                 | 143      |
| require                  | redaxo/index.php                         | 9        |

</details>
<details>
<summary>System report (REDAXO 5.13.2, PHP 8.1.8, MariaDB 10.2.44)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.2     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.8      |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MariaDB 10.2.44                |
| Character set | utf8mb4                        |
|       Warning | Die verwendete MariaDB-Version 10.2.44 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/15.5 |
|      Protocol | HTTP/1.0    |
|         HTTPS | yes         |

| Packages            |             |
| ------------------: | :---------- |
|             adminer | 1.9.2       |
|     article_presets | 1.2.0       |
|              backup | 2.8.0       |
|            be_style | 3.0.1       |
| be_style/customizer | 3.0.1       |
|     be_style/redaxo | 3.0.1       |
|                cke5 | 5.2.0-dev   |
|             collect | 0.0.7-dev   |
|         collect/rss | 0.0.1-dev   |
|       collect/vimeo | 0.0.1-dev   |
|             cronjob | 2.8.2       |
|         geolocation | 0.15.0      |
|            icecoder | 3.0.0       |
|             install | 2.9.3       |
|              mblock | 3.4.4       |
|       media_manager | 2.12.1      |
|           mediapool | 2.11.2      |
|            metainfo | 2.8.4       |
|       mf_modulsuche | 1.0         |
|               mform | 7.0.2       |
|    navigation_array | 1.2.0       |
|           phpmailer | 2.11.1      |
|                plyr | 3.14.0      |
|             project | dev         |
|          sachspende | 0.2         |
|       slice_columns | 1.0.0-beta4 |
|               staff | 1.0.0-dev   |
|           structure | 2.13.2      |
|   structure/content | 2.13.2      |
|    uikit_collection | 3.0.0       |
|               users | 2.8.2       |
|               yform | 4.0.2       |
|         yform/email | 4.0.2       |
|       yform/manager | 4.0.2       |
|         zip_install | 1.1         |

</details>

**Comment by alxndr-w** [comment]
Sachen gibt's. Ich hatte das bestimmt im Projekt gefixt und hier nie geupdatet, sondern mir nur den Addon Key gesichert.
